### ISSUE TITLE
RSA-SHA1 signing method is not working

### ISSUE THREAD

**Issue by Wirone** [guzzle/oauth-subscriber#15]
Problem is with these lines in `GuzzleHttp\Subscriber\Oauth\Oauth1::sign_RSA_SHA1()`:

``` php
$privateKey = openssl_pkey_get_private(
    file_get_contents($this->config['consumer_secret']),
    $this->config['consumer_secret']
);
```

We have to use `$this->config['consumer_secret']` for private key's path, but then `$this->config['consumer_secret']` is also used as passphrase and it's not working.

I have two ideas:
- there should be one additional `private_key` attribute in constructor's `$config` so `sign_RSA_SHA1()` could use `$this->config['private_key']`. Maybe `$this->config['private_key_passphrase']` also? In my opinion it would be most readable.
- `sign_RSA_SHA1()` could use `$this->config['consumer_key']` for private key's path and `$this->config['consumer_secret']` for optional passphrase. But it could be misleading.

**Comment by Wirone** [comment]
Great! When new release will be available for Composer?

**Comment by Brainshack** [comment]
Will there be a version of this fix for guzzle 5?

**Comment by Aerendir** [comment]
I think this can be closed...
