### ISSUE TITLE
How to create OAuth token and OAuth secret

### ISSUE THREAD

**Issue by BentCoder** [guzzle/oauth-subscriber#27]
Hi,

I'm trying to use this library but don't really know how to create OAuth token and OAuth secret. Would you please help me?

Thanks

```
$oauth_consumer_key = '6481-6163-0300';
$consumer_secret = '3qrq46dabjokwsgk4owwk8k4scs00o400kccwc0gs4048k8css';
$oauth_nonce = md5(uniqid(mt_rand(), true));
$oauth_version = "1.0";
$oauth_signature_method = "HMAC-SHA1";
$oauth_token = ???????????????
$oauth_secret = ???????????????
```

**Comment by mastacheata** [comment]
There are quite a few ways to acquire these. Which one you use depends on your environment and the service you are consuming.
For example Twitter provides you with an Access Token and Secret for your very own account without any prior authentication flow.
They also provide 2 options for acquiring access tokens and secrets for users of your application.
3-legged OAuth and OOB / Pin-based OAuth.
Check out this page in their developer docs:
https://dev.twitter.com/oauth

This isn't really about this library, though. You're having problems with the OAuth process itself and would probably get faster help when looking into the developer community of whatever service you want to consume.

**Comment by Aerendir** [comment]
I think this may be closed...
