### ISSUE TITLE
Guzzle 6 support

### ISSUE THREAD

**Issue by Vasiliskov** [guzzle/oauth-subscriber#34]
As Guzzle moved to version 6 there are some major changes that doesn't allow to easily adopt your code. I think quite a lot of people would really appreciate if you produce a solution for v6.

**Comment by cbakker** [comment]
I have added a PR for it: #36 

If you want to use it already, you can use this in your composer.json file:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:cbakker/oauth-subscriber.git"
        }
    ],
    "require": {
        "guzzlehttp/guzzle": "~6.0",
        "guzzlehttp/oauth-subscriber": "dev-master"
    },
```

**Comment by Aerendir** [comment]
Are there any plans on the update of this library?
