### ISSUE TITLE
Cant install via composer with guzzle 6

### ISSUE THREAD

**Issue by articfox1986** [guzzle/oauth-subscriber#43]
trying to install via composer and ive got the required packages set to
"guzzlehttp/guzzle": "~6.0",
"guzzlehttp/oauth-subscriber": "0.2.*",

But when doing a composer update I get:
Problem 1
    - guzzlehttp/oauth-subscriber 0.2.0 requires guzzlehttp/guzzle ~4.0|~5.0 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].
    - guzzlehttp/oauth-subscriber 0.2.0 requires guzzlehttp/guzzle ~4.0|~5.0 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.x-dev
    - Installation request for guzzlehttp/oauth-subscriber 0.2.* -> satisfiable by guzzlehttp/oauth-subscriber[0.2.0].

Ive tried minimum-stability on dev and stable

**Comment by kkopachev** [comment]
Readme has incorrect version. Use 0.3:
` "guzzlehttp/oauth-subscriber": "~0.3.0"`

**Comment by articfox1986** [comment]
Thanks that sorts it out
