### ISSUE TITLE
Why this repo seems to be dead?

### ISSUE THREAD

**Issue by Aerendir** [guzzle/oauth-subscriber#52]
There a lot of PR unmerged and also issues opened. Is there a reason why is all stopped?

**Comment by mtdowling** [comment]
I no longer can devote much time to this repo. If volunteers come forward, I can give more people commit access. I'd need to be familiar with their work and know the direction they'd take the project, but I'm happy to pass the torch.

**Comment by Aerendir** [comment]
Ok, thank you for your response... I'm going around the repo commenting to help you identify issues to close and PR to merge :)
