### ISSUE TITLE
Attempted to call function "parse_query" from namespace "GuzzleHttp\Psr7".

### ISSUE THREAD

**Issue by SergeC** [guzzle/oauth-subscriber#91]
**PHP version**: 7.4.12

**Description**
Getting an error "Attempted to call function "parse_query" from namespace "GuzzleHttp\Psr7"." In Oauth1.php line 149.
Seems like Guzzle moved functions to another place
Guzzle v7.3.0
oauth-subscriber v0.5.0

**How to reproduce**
Check functions locations. Functions called from old places

**Possible Solution**
Update library to be compatible with guzzle v7.3

**Additional context**

**Comment by SergeC** [comment]
The oauth-subscriber v0.5.0 works fine with Guzzle v7.2.0 but crashes with Guzzle v7.3.0.

**Comment by GrahamCampbell** [comment]
This should be fixed by https://github.com/guzzle/oauth-subscriber/pull/90.

**Comment by SergeC** [comment]
@GrahamCampbell looks good. Can we have it merged and tagged(released) ASAP?

**Comment by GrahamCampbell** [comment]
Fixed in 0.6.0.
