### ISSUE TITLE
Incompatible dependency. Use of GuzzleHttp\Psr7\parse_query()

### ISSUE THREAD

**Issue by kmuenkel** [guzzle/oauth-subscriber#93]
**PHP version**: 7.3.27

**Description**
The `Oauth1::getSignature()` is attempting to leverage `GuzzleHttp\Psr7\parse_query()`. Howevern the parse_query() was deprecated, and in later versions of GuzzleHttp\Psr7, unavailable. So updating these packages renders this one unusable.
The problem is simply that oauth-subscriber's composer.json isn't restrictive enough. It depends on '"guzzlehttp/guzzle": "^6.0|^7.0"', which in turn depends on '"guzzlehttp/psr7": "^1.7 || ^2.0",'. But guzzlehttp/psr7 v2.0 is what removes that function.

**How to reproduce**
Any use of the `Oauth1::getSignature()` method will trigger this.

**Possible Solution**
Either observe the deprecation notice's instructions and replace these function calls with `GuzzleHttp\Psr7\Query::parse()`, or just add a more-explicit dependency on guzzlehttp/psr7 that limits it to just '^1.7', and not '^2.0'.

**Comment by GrahamCampbell** [comment]
Already fixed.

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version.

**Comment by kmuenkel** [comment]
Ah.. sorry about that. Didn't realize I was behind.
