### ISSUE TITLE
Depricated function was removed

### ISSUE THREAD

**Issue by mzbiegien** [guzzle/oauth-subscriber#95]
**PHP version**: 8.1.3
**Guzzle version**: 7.4.1

**Description**
Function GuzzleHttp\Psr7\parse_query() used in Oauth1.php was removed and this leads to undefined function error.

**How to reproduce**
Using oauth-subscriber and Guzzle 7.4.1 run a signed oAuth query. 

**Possible Solution**
Code needs updating to Query::parse() and Query:build().

**Comment by GrahamCampbell** [comment]
This is already fixed in v0.6.0
